### ISSUE TITLE
error messages when browsing admin page

### ISSUE THREAD

**Issue by jim-bo** [CIMAC-CIDC/cidc-ui#88]
I get the following error message from browsing the admin page:

![image](https://user-images.githubusercontent.com/317043/63182873-8e939080-c021-11e9-9041-9efe1f085181.png)

**Comment by jacoblurye** [comment]
This is an SSL certificate issue with the old API. The portal still makes calls to the old API for certain things, and the old API's SSL setup is no longer valid. Once the portal no longer calls the old API, we'll stop seeing these errors. In the meantime, I'd recommend just setting up a security exception in your browser (this wouldn't be acceptable if real data were flowing in the system, but that isn't yet the case).

**Comment by jacoblurye** [comment]
Reopened, since this issue won't technically be resolved until we exclusively rely on the new API in the portal UI.

**Comment by jacoblurye** [comment]
https://github.com/CIMAC-CIDC/cidc-ui/pull/107
